apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: enonic-xp-deployment
  labels:
    app: enonic-xp-platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: enonic-xp-platform
        tier: web
    spec:
      containers:
        - name: enonic-xp-platform
          image: gcr.io/kubernetes-181111/enonic-xp-image
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: enonic-xp-persistent-storage
              mountPath: /enonic-xp/home/repo/
      volumes:
        - name: enonic-xp-persistent-storage
          gcePersistentDisk:
            pdName: enonic-xp-pdisk
            fsType: ext4
