apiVersion: v1
kind: Service
metadata:
  name: enonic-xp-deployment
  labels:
    app: enonic-xp-platform
spec:
  type: NodePort
  selector:
    app: enonic-xp-platform
    tier: web
  ports:
    - port: 80
      targetPort: 8080
